;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        counsel-find-file
        crux-move-beginning-of-line
        down-list
        electric-newline-and-maybe-indent
        eval-last-sexp
        forward-sexp
        indent-for-tab-command
        kill-region
        lsp-ui-doc--handle-mouse-movement
        org-end-of-line
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        handle-switch-frame
        org-delete-char
        ))
