(deftheme tarffienation
  "Created 2025-01-31.")

(custom-theme-set-faces
 'tarffienation
 '(cursor ((t (:background "#704B4B"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "red"))))
 '(homoglyph ((t (:foreground "red2"))))
 '(minibuffer-prompt ((t (:foreground "dark red"))))
 '(highlight ((t (:background "darkred" :foreground "white smoke"))))
 '(region ((t (:extend t :background "dark red"))))
 '(shadow ((t (:foreground "#5B6268"))))
 '(secondary-selection ((t (:extend t :background "#1B2229"))))
 '(trailing-whitespace ((t (:background "#ff6c6b"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:inherit bold :foreground "slate gray"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "PaleGreen1"))))
 '(font-lock-constant-face ((t (:foreground "dark red"))))
 '(font-lock-delimiter-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#81a155" :slant italic))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit font-lock-regexp-grouping-backslash))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "dark red" :inherit bold))))
 '(font-lock-keyword-face ((t (:foreground "dark gray" :inherit bold))))
 '(font-lock-negation-char-face ((t (:foreground "#bbc2cf" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "brown"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#bbc2cf" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#bbc2cf" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bbc2cf" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "brown"))))
 '(font-lock-type-face ((t (:inherit bold :foreground "red3"))))
 '(font-lock-variable-name-face ((t (:foreground "red2"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "dark red" :underline t :weight bold))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#3f444a" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#bbc2cf" :background "#1c1f24"))))
 '(mode-line ((t (:background "#1e2126"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#DFDFDF"))))
 '(mode-line-highlight ((t (:inherit highlight))))
 '(mode-line-inactive ((t (:foreground "#747295" :background "#000000"))))
 '(isearch ((t (:inherit lazy-highlight :weight bold))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "#ff6c6b"))))
 '(lazy-highlight ((t (:weight bold :foreground "#DFDFDF" :background "#004e85"))))
 '(match ((t (:weight bold :foreground "#98be65" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1D1C23" :foreground "#bbc2cf" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 180 :width normal :foundry "SAJA" :family "ComicShanns Mono Nerd Font")))))

(provide-theme 'tarffienation)
