[window]
startup_mode = "Fullscreen"
title = "Unholy Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"
padding = { x = 3, y = 3 }
dynamic_padding = true 
opacity = 0.85
decorations = "None"
[font]
size = 16
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
[colors.primary]
foreground = "#DEDEDE"
background = "#241F31"
