;;; .emacs -- Tarffie emacs config files
;;; commentary:
;;; the code is structured in sections and separeted in files.
;;; each section is identified by a commentary box and its subsections might or not be indicated by single
;;; line commentary.
;;; Code:

;;;;;;;;;;;;;;;;;;;;;
;;  init packages  ;;
;;;;;;;;;;;;;;;;;;;;;

;; repositories
(require 'package)
(setq package-archives '(("melpa" . "http://melpa.org/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/")))

;; add ELPA packages to load path
(let ((default-directory "~/.emacs.d/elpa"))
  (normal-top-level-add-subdirs-to-load-path))
(eval-when-compile
  (require 'use-package))

;;; default custom files and files auto generated by emacs
(setq custom-file "~/.custom.el")
(add-to-list 'load-path "~/.emacs.d/.emacs.local/")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; loading my custom files ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "~/.emacs.d/.emacs.rc/rc.el")

;; reading and writing files, also backups
(load "~/.emacs.d/tarffie-files.el")

;; (rc/require 'exec-path-from-shell)
;; (use-package exec-path-from-shell
;;   :ensure  t
;;   :config
;;   (exec-path-from-shell-initialize))

;;;;;;;;;;;;;;;;;
;;  apparence  ;;
;;;;;;;;;;;;;;;;;
(load-file "~/.emacs.d/tarffienation-theme.el")
(load-theme 'tarffienation t)
;; https://raw.githubusercontent.com/stackmystack/doom-moonfly-theme/refs/heads/master/doom-moonfly-theme.el
;;(rc/require 'doom-themes)
;;(load-file "~/.emacs.d/doom-moonfly-theme.el")

;; my favorite themes here so I can remember then later
;;(load-theme 'doom-moonfly t)
;;(load-theme 'doom-challenger-deep t)
;;(load-theme 'doom-homage-black t)
;;(load-theme 'doom-plain-dark t)
;;(load-theme 'doom-flatwhite t)

;; I might feel nostalgic later.
;;(rc/require-theme 'catppuccin)
;;(setq-default catppuccin-flavor 'macchiato) ; or 'latte, 'macchiato, or 'mocha

(set-face-attribute 'default nil
                    :family "Comic Shanns Mono Nerd Font Mono"
                    :height 180
                    :weight 'normal
                    :width 'normal)
(set-face-attribute 'region nil :background "#382487")

(setq display-line-numbers-width 2)
(global-hl-line-mode 1)

(repeat-mode 1)
(tab-bar-mode 0)
(set-scroll-bar-mode nil)
(setq-default cursor-type 'box)
(setq-default blink-cursor-mode nil)
(tool-bar-mode 0)
(menu-bar-mode 0)
(set-fringe-style 0)

(add-hook 'prog-mode-hook #'display-line-numbers-mode)

(setq-default inhibit-startup-screen t)
(setq-default display-line-numbers-type 'relative)

;; Make frames transparent

(set-frame-parameter (selected-frame) 'alpha-background 85)
(add-to-list 'default-frame-alist '(alpha-background .  85))
(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
(add-to-list 'default-frame-alist '(fullscreen . maximized))

(setq frame-background-mode nil
      column-number-mode t
      frame-title-format (concat invocation-name "@" (system-name) "{%f}")
      ;; no visible or audible bells, please
      visible-bell t
      ring-bell-function (lambda nil (message "")))

;;;;;;;;;;;;;;;;;
;;  eye candy  ;;
;;;;;;;;;;;;;;;;;

;; moody for buffer like tabs
(rc/require 'moody)
(use-package moody
  :config
  (moody-replace-mode-line-front-space)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))

(rc/require 'hide-mode-line)
(add-hook 'eshell-mode-hook #'hide-mode-line-mode)

;;  may or may not remove this one

(setq show-paren-style 'mixed)

(use-package paren)
(set-face-background 'show-paren-match (face-background 'default))
(set-face-attribute 'show-paren-match nil :weight 'extra-bold)

;; juts because this is really annoying with eglot
(add-to-list 'warning-suppress-types '(emacs))

;;;;;;;;;;;;;;;;
;; navigation ;;
;;;;;;;;;;;;;;;;

;; open file or definition

;; open terminal
;; replaced term with vterm because it can actually run TUI apps
(rc/require 'multi-vterm)
(global-set-key (kbd "s-t") 'multi-vterm)
(global-set-key (kbd "C-x v p") 'multi-vterm-prev)
(global-set-key (kbd "C-x v n") 'multi-vterm-next)

(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                eshell-mode-hook
                compilation-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

;; navigate between visible buffers (windows in emacs speak)
(defun other-window-backward (&optional n)
  "Interactive function called when you wanna swap visible buffer.
where as N is the active buffer number, which will be replaced"

  (interactive "p")
  (if n
      (other-window (- n))
    (other-frame -1)))
(global-set-key "\C-x\C-n" 'other-window)
(global-set-key "\C-x\C-p" 'other-window-backward)

;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                      ;;
;;  text/code editing   ;;
;;                      ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;

;; prefer to use
(prefer-coding-system 'utf-8-unix)

;; I really love emacs copy paste except because it doesn't kill the region before yanking
(defun paste-like-vim (beg end)
  "Receives region (as BEG and END), yank text to it and `'kill-region'`.
and replace copy-ring entry, behaving similarly to
the vi text editor family yank-paste functionality."
  (interactive "r")
  (if (use-region-p)
      (progn
        (if (markerp nil)
            (set-marker 0 0))
        (yank)
        (kill-region beg end))
    (yank)))

;; whitespaces!
(add-hook 'python-mode-hook #'whitespace-mode)

;;;;;;;;;;;;;;;;;;;;;
;; custom bindings ;;
;;;;;;;;;;;;;;;;;;;;;

(global-set-key (kbd "C-y") 'paste-like-vim)
(global-set-key (kbd "M-d") 'backward-delete-char-untabify)

;; had that in vim and never learned to live without
(global-set-key "\C-u" 'scroll-down)

;; binding to stop evaluating stuff when I just don't wanna press enter
(global-set-key "\C-j" 'newline-and-indent)

;; I really hate this but I Know why i have it.
(global-unset-key "\C-t")

;; the binding to stop minimizing emacs by accident
(global-unset-key "\C-z")

;; i like my auto formating :(
(rc/require 'format-all)
(use-package format-all
  :preface
  (defun tarffie/format-code ()
    "Auto-format whole buffer."
    (interactive)
    (format-all-ensure-formatter)
    (cond
     ((or (derived-mode-p 'java-mode) (derived-mode-p 'java-ts-mode))
      (eglot-format-buffer))
     ((or (derived-mode-p 'php-mode) (derived-mode-p 'php-ts-mode))
      (lsp-format-buffer))
     ((derived-mode-p 'prolog-mode)
      (prolog-indent-buffer))
     (t
      (format-all-buffer))))
  :config
  (add-hook 'prog-mode #'format-all-ensure-formatter))
(global-set-key (kbd "C-x f") #'tarffie/format-code)

;; don't write backslashed to indicate continuous lines
(set-display-table-slot standard-display-table 'wrap ?\ )

;; it doesn't really make sense for it to just comment and not uncomment
(global-set-key (kbd "C-c C-c") 'comment-or-uncomment-region)

(global-unset-key (kbd "C-c f"))

;; treat y as yes n as no
(fset 'yes-or-no-p 'y-or-n-p)

(global-set-key "\C-cn" 'find-dired)
(global-set-key "\C-cN" 'grep-find)

;; crux ;;
(rc/require 'crux)
(setq save-abbrevs 'silently)
(setq-default abbrev-mode t)
(global-set-key (kbd "C-a") 'crux-move-beginning-of-line)

;; Move Text ;;
(rc/require 'move-text)
(global-set-key (kbd "M-P") 'move-text-up)
(global-set-key (kbd "M-N") 'move-text-down)

(use-package grep)
(setq grep-find-ignored-directories
      (append
       (list
        ".git"
        ".hg"
        ".idea"
        ".project"
        ".settings"
        ".svn"
        "bootstrap*"
        "pyenv"
        "target"
        )
       grep-find-ignored-directories))

(setq grep-find-ignored-files
      (append
       (list
        "*.blob"
        "*.xd"
        "TAGS"
        "dependency-reduced-pom.xml"
        "projectile.cache"
        "workbench.xmi"
        )
       grep-find-ignored-files))

(setq grep-find-command
      "find ~/src/content-engine -name \"*.java\" | xargs grep -n -i -e ")
(rc/require 'ag)
(use-package ag
  :init
  (setq ag-arguments (list "--word-regexp" "--smart-case"))
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;; tab size and white spaces ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Tabs to spaces
(setq-default indent-tabs-mode 'complete
	            tab-width 2
              c-basic-offset tab-width
              java-ts-basic-offset tab-width
              java-basic-offset tab-width
							rust-ts-mode-indent-offset tab-width)


;; tarffie note here:
;; ngl i have no idea what this does or why I put it here in the first place
;; coding java in emacs was wild..
;;; non sense section
;; ws-butler cleans up whitespace only on the lines you've edited,
;; keeping messy colleagues happy ;-) Important that it doesn't clean
;; the whitespace on currrent line, otherwise, eclim leaves messy
;; code behind.
																				;(rc/require 'ws-butler)
																				;(use-package ws-butler
																				;  :init
																				;  (setq ws-butler-keep-whitespace-before-point nil)
																				;  :config
																				;  (ws-butler-global-mode))

;;;;;;;;;;;;;;;;
;; minibuffer ;;
;;;;;;;;;;;;;;;;

(load "~/.emacs.d/minibuffer.el")

;;;;;;;;;;;;;;;;;;;;;;;;
;; Mode line settings ;;
;;;;;;;;;;;;;;;;;;;;;;;;

(load "~/.emacs.d/modeline.el")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Code editing, typing and text editing in general
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (add-hook 'text-mode-hook
;;           #'(lambda ()
;;               (flyspell-mode)
;;               (auto-fill-mode 1)))
(setq-default longlines-show-hard-newlines t)


(global-set-key "\C-x\C-c" 'compile) ;; imenu
(global-set-key (kbd "<C-S-f10>") 'recompile)
(global-set-key (kbd "<C-tab>") 'completion-at-point)

;; newline and indent (like other editors, even vi, do).
(global-set-key  "\C-m" 'newline-and-indent)

;; Automatically reload files was modified by external program
(global-set-key  [ (f5) ] 'revert-buffer)
(global-auto-revert-mode 1)
(setq-default revert-without-query (list "\\.png$" "\\.svg$")
              auto-revert-verbose nil)

;; Give visual hint where the cursor is when switching buffers.
(rc/require 'beacon)
(use-package beacon
  :config
  (beacon-mode 1))

;;;;;;;;;;;;;;;;;;;;;
;; compiler buffer ;;
;;;;;;;;;;;;;;;;;;;;;
(load "~/.emacs.d/compile.el")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Editing VC log messages
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(add-hook 'log-edit-hook (lambda () (flyspell-mode 1)))

;;; multiple cursors
(rc/require 'multiple-cursors 'expand-region)


(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C->")         'mc/mark-next-like-this)
(global-set-key (kbd "C-<")         'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<")     'mc/mark-all-like-this)
(global-set-key (kbd "C-\"")        'mc/skip-to-next-like-this)
(global-set-key (kbd "C-:")         'mc/skip-to-previous-like-this)

(use-package expand-region
  :bind
  ("C-=" . 'er/expand-region))

(global-set-key (kbd "C-c d s") 'eldoc-print-current-symbol-info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ivy, counsel and swiper. Mostly minibuffer and navigation
;; enhancements.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "~/.emacs.d/tarffie-ivy.el")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Buffers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Make C-x C-b maximise the buffer list window, this saves two
;; additional shortcuts from the normal behaviour. [thanks tkj]
(defun tkj-list-buffers()
  "List all buffers with colors and fancy commands."
  (interactive)
  (let ((helm-full-frame t))
    (helm-mini)))
(global-unset-key "\C-x\C-b")
(global-set-key "\C-x\C-b" 'tkj-list-buffers)

(defun close-all-buffers ()
  "Close all open buffers."
  (interactive)
  (mapc 'kill-buffer (buffer-list)))

;; buffer names and mini buffer
(use-package uniquify
  :init
  (setq uniquify-buffer-name-style 'forward
        uniquify-separator ":"
        uniquify-strip-common-suffix nil
        read-file-name-completion-ignore-case t))

;; Auto scroll the compilation window
(setq compilation-scroll-output t)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Search
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(rc/require 'helm-swoop)
(use-package helm-swoop
  :bind
  ("M-n" . helm-swoop))

(rc/require 'helm-projectile)
(use-package helm-projectile
  :bind
  ("C-'" . helm-projectile-grep))

(global-set-key (kbd "C-s") 'swiper)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                  ;;
;;     Highlighting and parsing     ;;
;;                                  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; CSS mode

(load "~/.emacs.d/tarffie-css.el")

;;;;;;;;;;;;;;;;;;;;;
;; Hippe expansion ;;
;;;;;;;;;;;;;;;;;;;;;

(rc/require 'hippie-exp)
(autoload 'hippie-exp "hippie-exp" t)

;;;;;;;;;;;;;;
;; Markdown ;;
;;;;;;;;;;;;;;
(rc/require 'markdown-ts-mode 'markdownfmt)
(add-hook 'markdown-mode-hook 'flyspell-mode)

;;;;;;;;;;;;;;;;
;; Yasnippets ;;
;;;;;;;;;;;;;;;;

(rc/require 'yasnippet)

(use-package yasnippet
  :ensure t
  :config

  (setq yas/root-directory
        (list "~/.emacs.d/snippets")
        yas-indent-line 'fixed)
  (yas-global-mode))

;;;;;;;;;
;; SQL ;;
;;;;;;;;;

(add-hook 'sql-interactive-mode-hook
          #'(lambda ()
              (company-mode)))

;;;;;;;;;;;;;;;;;
;; Web browser ;;
;;;;;;;;;;;;;;;;;

(setq browse-url-generic-program "chrome"
      browse-url-browser-function 'browse-url-generic)

;;;;;;;;;;;;;;;;;;;;;
;; Emacs behaviour ;;
;;;;;;;;;;;;;;;;;;;;;

(setq-default warning-suppress-types (quote ((undo discard-info))))

;;;;;;;;;;;;;;;
;; js && ts  ;;
;;;;;;;;;;;;;;;

(load "~/.emacs.d/tarffie-js.el")

;;;;;;;;;;;;;;;;;;;;;
;;   lean4 mode    ;;
;;;;;;;;;;;;;;;;;;;;;

(load "~/.emacs.d/tarffie-lean.el")

;;;;;;;;;;;;
;; Unfill ;;
;;;;;;;;;;;;

(defun unfill-paragraph ()
  "Collapse paragrah."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))

(defun unfill-region ()
  "Collapse region."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-region (region-beginning) (region-end) nil)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Tidy
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun tidy-buffer ()
  "Run Tidy HTML parser on current buffer."
  (interactive)
  (if (get-buffer "tidy-errs") (kill-buffer "tidy-errs"))
  (shell-command-on-region (point-min) (point-max)
                           "tidy -f /tmp/tidy-errs -q -wrap 72" t)
  (find-file-other-window "/tmp/tidy-errs")
  (other-window 1)
  (delete-file "/tmp/tidy-errs")
  (message "buffer tidy-ed"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Diff
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(setq-default ediff-window-setup-function 'ediff-setup-windows-plain
              ediff-split-window-function 'split-window-horizontally ;; !work
              ediff-diff-options "-w"
              smerge-command-prefix "\C-cv")
;; Restore window/buffers when you're finishd ediff-ing.
(add-hook 'ediff-after-quit-hook-internal 'winner-undo)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; org-mode && notes
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "~/.emacs.d/custom-org.el") ;; TODO

(defun open-notes ()
  "Interactive function to launch my personal notes.org file."
  (interactive)
  (defconst file-path "~/notes/notes.org")
  (if (file-exists-p file-path)
      (find-file-at-point file-path)
    (if (not #'directory-empty-p)
        (mkdir "~/notes/"))
    (find-file file-path)
    (save-buffer)))
(global-set-key (kbd "C-x D") #'open-notes)

(defun open-yt-description ()
  "Interactive function to launch my youtube-description file while live-streaming."
  (interactive)
  (defconst file-path "~/notes/videos/description.org")
  (if (file-exists-p file-path)
      (find-file-at-point file-path)
    (if (not #'directory-empty-p)
        (mkdir --parents "~/notes/videos"))
    (find-file file-path)
    (save-buffer)))
(global-set-key (kbd "C-x y d") #'open-yt-description)

;;Allow interactive narrow-to-region
(put 'narrow-to-region 'disabled nil)

(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)

(rc/require 'lsp-mode)
(rc/require 'lsp-ui)
(require 'lsp-mode)
(require 'lsp-ui)

(rc/require 'flycheck)
(rc/require 'lsp-treemacs)

(global-set-key (kbd "C-t") 'treemacs)

(global-set-key (kbd "C-x R") #'lsp-rename)

(rc/require 'helm-lsp)
(use-package helm-lsp :commands helm-lsp-workspace-symbol)

(rc/require 'tree-sitter)
(rc/require 'tree-sitter-langs)
(rc/require 'treesit-auto)

;;;;;;;;;;;;;
;; company ;;
;;;;;;;;;;;;;

(rc/require 'company)
(rc/require 'company-emoji)

(use-package company
  :ensure t
  :config
  (global-set-key (kbd "<C-return>") 'company-complete)
  (global-company-mode 1))

(setq company-idle-delay 0.75)
(setq-default company-prefix-min-length 3)

;; Get auto completion of :emoji: names.
(use-package company-emoji
  :ensure t
  :after company-mode
  :config
  (company-emoji-init))

(add-to-list 'company-backends 'company-emoji)

;;;;;;;;;;
;; java ;;
;;;;;;;;;;

(load-file "~/.emacs.d/tarffie-java.el")
;; end of java config

(rc/require 'smartparens)

(use-package smartparens
  :ensure t
  :demand t
  :config
  (require 'smartparens-config)
  (smartparens-global-mode 1)
  (setq-default show-smartparens-global-mode 1)
  (sp-pair "{" nil :post-handlers '(("||\n[i]" "RET")))
  (sp-pair "[" nil :post-handlers '(("||\n[i]" "RET")))
  (sp-pair "(" nil :post-handlers '(("||\n[i]" "RET"))))

;;; dired
(require 'dired-x)
(setq dired-omit-files
      (concat dired-omit-files "\\|^\\..+$"))
(setq-default dired-dwim-target t)
(setq dired-listing-switches "-alh")

;;; helm
(rc/require 'helm  'helm-git-grep 'helm-ls-git)
(setq helm-ff-transformer-show-only-basename nil)
(global-set-key (kbd "C-c h t") 'helm-cmd-t)
(global-set-key (kbd "C-c h g l") 'helm-ls-git-ls)
(global-set-key (kbd "C-c h f") 'helm-find)
(global-set-key (kbd "C-c h a") 'helm-org-agenda-files-headings)
(global-set-key (kbd "C-c h r") 'helm-recentf)

;;; harpoon
(rc/require 'harpoon 'hydra)

(global-set-key (kbd "C-c SPC") 'harpoon-quick-menu-hydra)
(global-set-key (kbd "C-c a") 'harpoon-add-file)
(global-set-key (kbd "C-c h e") 'harpoon-toggle-quick-menu)
(global-set-key (kbd "C-c h c") 'harpoon-clear)
(global-set-key (kbd "C-c h 1") 'harpoon-go-to-1)
(global-set-key (kbd "C-c h 2") 'harpoon-go-to-2)
(global-set-key (kbd "C-c h 3") 'harpoon-go-to-3)
(global-set-key (kbd "C-c h 4") 'harpoon-go-to-4)
(global-set-key (kbd "C-c h 5") 'harpoon-go-to-5)
(global-set-key (kbd "C-c h 6") 'harpoon-go-to-6)
(global-set-key (kbd "C-c h 7") 'harpoon-go-to-7)
(global-set-key (kbd "C-c h 8") 'harpoon-go-to-8)
(global-set-key (kbd "C-c h 9") 'harpoon-go-to-9)

;; ocaml??
(load "~/.emacs.d/ocaml.el")
(load "~/.emacs.d/opam-user-setup.el")

;; Presence.el because I like discord interaction
;; https://github.com/richardhbtz/emacs-rpc
;; (rc/require 'elcord)
;; (elcord-mode)

;; ultra-scroll
;;
(use-package ultra-scroll
  :vc (:url "https://github.com/jdtsmith/ultra-scroll")
  :init
  (setq scroll-conservatively 101 ; important!
        scroll-margin 0)
  :config
  (pixel-scroll-precision-mode t))

;;(load "~/.emacs.d/tarffie-lisp.el")

(add-hook 'lean4-mode-hook 'smartparens-mode)

;; Rust programming language
;; (load "~/.emacs.d/tarffie-rust.el")

;; Magit
(rc/require 'magit)

;; C programming language lsp
(add-hook 'c-mode-hook 'eglot-ensure)
(add-hook 'c++-mode-hook 'eglot-ensure)

(provide '.emacs)
;;; .emacs.el ends here
